#!/usr/bin/env bash

# Age
# osca_Linux --befile /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_mvals_fixedage_commonsnps --pheno /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_age.txt --qcovar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_qcovar.txt --covar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_covar_nowave.txt --linear --fast-linear --out /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/osca/w1w3w4/gs20k_age  
osca_Linux --befile /Cluster_Filespace/Marioni_Group/Elena/gs_osca/data/mvals-norm20k-18413-831733 --pheno /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_age.txt --qcovar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_qcovar.txt --covar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_covar_nowave.txt --linear --fast-linear --out /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/osca/w1w3w4/gs20k_age

# Age^2
# osca_Linux --befile /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_mvals_fixedage_commonsnps --pheno /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_age2.txt --qcovar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_qcovar_withage.txt --covar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_covar_nowave.txt --linear --fast-linear --out /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/osca/w1w3w4/gs20k_age2
osca_Linux --befile /Cluster_Filespace/Marioni_Group/Elena/gs_osca/data/mvals-norm20k-18413-831733 --pheno /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_age2.txt --qcovar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_qcovar_withage.txt --covar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_covar_nowave.txt --linear --fast-linear --out /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/osca/w1w3w4/gs20k_age2

# CpG^2
# osca_Linux --befile /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_mvals_squared_fixedage_commonsnps --pheno /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_age.txt --qcovar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_qcovar.txt --covar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_covar_nowave.txt --linear --fast-linear --out /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/osca/w1w3w4/gs20k_cpg2
# osca_Linux --befile /Cluster_Filespace/Marioni_Group/Elena/gs_osca/data/mvals-norm20k-18413-831733 --extract-probe /Cluster_Filespace/Marioni_Group/Elena/gs_osca/data/cpgs_tokeep.txt --pheno /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_age.txt --qcovar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_qcovar.txt --covar /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/data_prep/w1w3w4/gs20k_covar_nowave.txt --linear --fast-linear --out /Cluster_Filespace/Marioni_Group/Elena/epigenetic_clocks/age_ewas/osca/w1w3w4/gs20k_cpg2
